apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analyticEnvironment.fullname" . }}
  labels:
    {{- include "analyticEnvironment.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analyticEnvironment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "analyticEnvironment.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.rstudio.persistentStorage.firstVolName }}
          persistentVolumeClaim:
            claimName: {{ .Values.rstudio.persistentStorage.firstClaimName }}
      containers:
        - name: {{ .Values.rstudio.podName }}
          image: "{{ .Values.rstudio.imageRepository }}:{{ .Values.rstudio.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rstudio.imagePullPolicy }}
          ports:
            - name: rstudio
              containerPort: {{ .Values.rstudio.service.rstudioPort }}
            - name: shiny
              containerPort: {{ .Values.rstudio.service.shinyPort }}
          volumeMounts:
            - mountPath: {{ .Values.rstudio.persistentStorage.firstMountPath }}
              name: {{ .Values.rstudio.persistentStorage.firstVolName }}
          env:
            - name: {{ .Values.rstudio.env.firstEnvName }}  #PASSWORD
              value: {{ .Values.rstudio.env.firstEnvValue }} #"mypass"
            - name: {{ .Values.rstudio.env.secondEnvName }} #ROOT
              value: {{ quote .Values.rstudio.env.secondEnvValue }} #"TRUE"
            - name: ADD
              value: shiny
      initContainers:
        - name: changeowner-one
          image: busybox
          command: ["chown","-R","1000:1000","/home/rstudio/project-analytics-files"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: {{ .Values.rstudio.persistentStorage.firstVolName }}
              mountPath: {{ .Values.rstudio.persistentStorage.firstMountPath }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
