apiVersion: v1
kind: Service
metadata:
  name: {{ include "analyticEnvironment.fullname" . }}
  labels:
    {{- include "analyticEnvironment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rstudio.service.type }}
  ports:
    - name: rstudio
      protocol: {{ .Values.rstudio.service.portProtocol }}
      port: {{ .Values.rstudio.service.rstudioPort }}
      nodePort: {{ .Values.rstudio.service.rstudioNodePort }}
    - name: shiny
      protocol: {{ .Values.rstudio.service.portProtocol }}
      port: {{ .Values.rstudio.service.shinyPort }}
      nodePort: {{ .Values.rstudio.service.shinyNodePort }}
      
  selector:
    {{- include "analyticEnvironment.selectorLabels" . | nindent 4 }}


